
services:
  scraper:
    build: .
    container_name: instagram_scraper
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
