
services:
  scraper:
    build: .
    container_name: instagram_scraper
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ../Staging:/downloads
    restart: unless-stopped
